// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhF5iLvO5RZV7Z6oUdwTKeR89u8FekgZ0',
    appId: '1:96083917262:web:f8a2533c5f040d15aad39f',
    messagingSenderId: '96083917262',
    projectId: 'get-lms-flutter',
    authDomain: 'get-lms-flutter.firebaseapp.com',
    storageBucket: 'get-lms-flutter.appspot.com',
    measurementId: 'G-8S2CK6V1BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv72hFs4-Be3BTdDiJyXEBSbelcxGBLBc',
    appId: '1:96083917262:android:3e8bfce72f4fd7c8aad39f',
    messagingSenderId: '96083917262',
    projectId: 'get-lms-flutter',
    storageBucket: 'get-lms-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNuvqt86ojPuBSKNtC4Ei1Rg-Mjkknho',
    appId: '1:96083917262:ios:e969ba7df936bf6faad39f',
    messagingSenderId: '96083917262',
    projectId: 'get-lms-flutter',
    storageBucket: 'get-lms-flutter.appspot.com',
    iosBundleId: 'com.example.getLmsFlutter',
  );
}
