name: get_lms_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.0
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.2
  country_code_picker: ^3.0.0
  phone_numbers_parser: ^8.2.0
  webview_flutter: ^4.7.0
  pin_code_fields: ^8.0.1
  shimmer_animation: ^2.1.0+1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  file_picker: ^8.0.0+1
  flutter_local_notifications: ^19.3.0
  universal_html: ^2.2.4
  flutter_inappwebview: ^6.0.0
  pdf:
  fluttertoast: ^8.2.2
  flutter_downloader: ^1.11.3
  universal_platform: ^1.0.0+1
  flutter_html:
  flutter_typeahead: ^4.8.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  dotted_border: ^2.1.0
  google_sign_in: ^7.1.0
  flutter_facebook_auth: ^6.0.4
  permission_handler: ^11.2.0
  youtube_player_iframe: ^5.1.2

  # Platform-specific dependencies to resolve plugin issues
  file_selector_linux: ^0.9.3+2
  file_selector_macos: ^0.9.4+3
  file_selector_windows: ^0.9.3+4
  flutter_local_notifications_linux: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
